name = "Ivan Kuleshov"
description = "Hardware Hacker, Systems Engineer"
keywords = ""
image = "merocle.jpg"
theme = "dark"
primary_color = "#d8831b"
text_align = "center"
gtag_id = "G-VNYMS2ZK97"

[[sections]]
title = "Links"
description = ""
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Uptime Lab"
description = "My blog"
url = "https://uplab.pro/"
[[sections.items]]
title = "Uptime Industries"
description = "A company on whose behalf awesome products are or will be sold"
url = "https://uptime.industries/"
[[sections.items]]
title = "I'm on X"
description = "Formerly Twitter"
url = "https://twitter.com/Merocle"

[[sections]]
title = "more links"
description = "many other links"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "Uplab.pro/ls"
url = "https://uplab.pro/ls"
